package task;

public enum ConfigEnum {
    SOURCE_FILE, NUM_AMOUNT_OF_TEST_DATA,
    CHUNK, FROM_SOURCE_CHUNK,
    MAX_INT, BUFFER_READ_SIZE,
    BUFFER_SIZE_RESULT_FILE,
    RESULT_FILE, DIR_FOR_TEMP_FILES
}
